=== vrkit-platform/vrkit-platform/etc/schema/models/DashboardConfig.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/DashboardConfig",
    "definitions": {
        "DashboardConfig": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "screens": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.UI.Screen"
                            },
                            "type": "array"
                        }
                    ]
                },
                "overlays": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.UI.Dashboard.Overlay"
                            },
                            "type": "array"
                        }
                    ]
                },
                "layouts": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.UI.Dashboard.OverlayLayout"
                            },
                            "type": "array"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Dashboard Config"
        },
        "IRacingTools.Models.UI.Dashboard.Overlay": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "kind": {
                    "enum": [
                        "OK_TRACK_MAP",
                        0
                    ],
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "title": "Overlay Kind"
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "description": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "parameters": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "object"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Overlay"
        },
        "IRacingTools.Models.UI.Dashboard.OverlayLayout": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "screenId": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "kind": {
                    "enum": [
                        "SK_MONITOR",
                        0,
                        "SK_VR",
                        1
                    ],
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "title": "Screen Kind"
                },
                "placements": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.UI.Dashboard.OverlayPlacement"
                            },
                            "type": "array"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Overlay Layout"
        },
        "IRacingTools.Models.UI.Dashboard.OverlayPlacement": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "overlayId": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "rect": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.RectI",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "parameters": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "object"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Overlay Placement"
        },
        "IRacingTools.Models.UI.Display": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "rect": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.RectI",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Display"
        },
        "IRacingTools.Models.UI.DisplayLayout": {
            "properties": {
                "origin": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.Position",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "displays": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.UI.Display"
                            },
                            "type": "array"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Display Layout"
        },
        "IRacingTools.Models.UI.Position": {
            "properties": {
                "x": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "y": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Position"
        },
        "IRacingTools.Models.UI.RectI": {
            "properties": {
                "size": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.SizeI",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "position": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.Position",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Rect I"
        },
        "IRacingTools.Models.UI.Screen": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ],
                    "description": "* Must serve as a hash"
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "kind": {
                    "enum": [
                        "SK_MONITOR",
                        0,
                        "SK_VR",
                        1
                    ],
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "title": "Screen Kind"
                },
                "size": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.SizeI",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "display": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.DisplayLayout",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "vr": {
                    "$ref": "#/definitions/IRacingTools.Models.UI.VRLayout",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Screen",
            "description": "* Represents a complete screen"
        },
        "IRacingTools.Models.UI.SizeI": {
            "properties": {
                "width": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "height": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Size I"
        },
        "IRacingTools.Models.UI.VRLayout": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "scale": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "number"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "VR Layout"
        }
    }
}

=== vrkit-platform/vrkit-platform/data/dashboards/simple-track-map.dashboard.irt.json
{
  "id": "simple-track-map",
  "name": "Simple Track Map",
  "screens": [
    {
      "id": "screen_displays",
      "name": "displays",
      "kind": "SK_MONITOR",
      "display": {
        "displays": [
        ],
        "origin": {
          "x": 0,
          "y": 0
        }
      }
    }
  ],
  "overlays": [
    {
      "kind": "OK_TRACK_MAP",
      "name": "Track Map",
      "id": "track-map-01",
      "parameters": {}
    }
  ],
  "layouts": [
    {
      "id": "display-layout",
      "name": "display-layout",
      "screenId": "screen_displays",
      "placements": [
        {
          "id": "display-track-map",
          "overlayId": "track-map-01",
          "parameters": {},
          "rect": {
            "position": {
              "x": 50,
              "y": 50
            }
          }
        }
      ]
    }
  ]
}
