=== vrkit-platform/vrkit-platform/etc/schema/models/PluginManifest.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/PluginManifest",
    "definitions": {
        "IRacingTools.Models.PluginComponentDefinition": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "type": {
                    "enum": [
                        "PLUGIN_COMPONENT_TYPE_OVERLAY",
                        0
                    ],
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "title": "Plugin Component Type"
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "description": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "supportedGames": {
                    "items": {
                        "enum": [
                            "SUPPORTED_GAME_IRACING",
                            0
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "array"
                        }
                    ],
                    "title": "Supported Game"
                },
                "commonParameters": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "object"
                        }
                    ],
                    "description": "* Common parameters irrespective of game or component type"
                },
                "overlayCommonSettings": {
                    "$ref": "#/definitions/IRacingTools.Models.PluginComponentDefinition.OverlayCommonSettings",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "overlayIrSettings": {
                    "$ref": "#/definitions/IRacingTools.Models.PluginComponentDefinition.OverlayIRSettings",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ],
                    "description": "IROverlaySettings, can be omitted"
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Plugin Component Definition"
        },
        "IRacingTools.Models.PluginComponentDefinition.OverlayCommonSettings": {
            "properties": {
                "fps": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "FPS OVERRIDING USER/APP CONFIGURED \u003c 1: USER/APP ARE USED TO CONFIGURE, DEFAULT VALUE (0) USES THE INTERNAL DEFAULT OF 10FPS"
                },
                "initialSize": {
                    "$ref": "#/definitions/IRacingTools.Models.SizeI",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ],
                    "description": "THIS IS REQUIRED"
                },
                "forceAspectRatio": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "boolean"
                        }
                    ],
                    "description": "THE ACTUAL ASPECT RATIO IS EXTRAPOLATED FROM `initial_size` PROVIDED"
                },
                "canResize": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "boolean"
                        }
                    ],
                    "description": "CAN THE OVERLAY BE RESIZED"
                },
                "visibleWithoutConnection": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "boolean"
                        }
                    ],
                    "description": "VISIBLE REGARDLESS OF AN ACTIVE GAME RUNNING"
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Overlay Common Settings",
            "description": "* Common Overlay specific settings"
        },
        "IRacingTools.Models.PluginComponentDefinition.OverlayIRSettings": {
            "properties": {
                "dataVariablesUsed": {
                    "items": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "array"
                        }
                    ]
                },
                "parameters": {
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "object"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Overlay IR Settings",
            "description": "* IRacing Overlay specific settings"
        },
        "IRacingTools.Models.PluginManifest.PluginAuthor": {
            "properties": {
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "company": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "email": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Plugin Author"
        },
        "IRacingTools.Models.SizeI": {
            "properties": {
                "width": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "height": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Size I"
        },
        "PluginManifest": {
            "properties": {
                "id": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "name": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "description": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "author": {
                    "$ref": "#/definitions/IRacingTools.Models.PluginManifest.PluginAuthor",
                    "additionalProperties": true,
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {}
                    ]
                },
                "components": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "items": {
                                "$ref": "#/definitions/IRacingTools.Models.PluginComponentDefinition"
                            },
                            "type": "array"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object"
                }
            ],
            "title": "Plugin Manifest"
        }
    }
}

=== vrkit-platform/vrkit-platform/docs/Design/PluginSystem/PluginManifestExample.plugin-manifest.json
{
  "id": "mycorp::myplugin",
  "author": {
    "company": "3FV",
    "name": "Jonathan Glanz",
    "email": "jonathan.glanz@gmail.com"
  },
  "name": "VRKitExternalPlugin",
  "components": [
    {
      "id": "leaderboard-overlay",
      "type": "PLUGIN_COMPONENT_TYPE_OVERLAY",
      "name": "Leaderboard",
      "description": "A configurable leaderboard overlay",
      "supportedGames": [
        "SUPPORTED_GAME_IRACING"
      ],
      "userSettings": {
        "carClassColor1": {
          "type":"color",
          "default": "#FF0000"
        },
        "carClassColor2": {
          "type":"color",
          "default": "#00FF00"
        },
        "carClassColor3": {
          "type":"color",
          "default": "#0000FF"
        }
      },
      "overlayCommonSettings": {
        "canResize": true,
        "forceAspectRatio": false,
        "fps": 0,
        "initialSize": {
          "height": 300,
          "width": 400
        }
      },
      "overlayIracingSettings": {
        "dataVariablesUsed": [
          "PlayerCarIdx",
          "CarIdxLap",
          "CarIdxLapCompleted",
          "CarIdxPosition",
          "CarIdxClassPosition",
          "CarIdxEstTime",
          "CarIdxLapDistPct"
        ]
      }
    }
  ]
}
